### ISSUE TITLE
Can you put this in an HTML file?

### ISSUE THREAD

**Issue by TheRealDigitalMaster** [PoiXson/pxnBackrooms-mirror#1]
I don't know how to run this repo in a website without an HTML file (I am on chromebook but my linux is blocked by restrictions).

**Comment by lorenzop** [comment]
I'm making a website for the plugin http://backrooms.poixson.com/

I'll also add a readme so it's more clear what this repo does. This is a bukkit/spigot plugin which generates the backrooms levels in minecraft.
