### ISSUE TITLE
Request for slighty tweaked generation of hotel rooms, so it can support specific look.

### ISSUE THREAD

**Issue by AnatomyKing** [PoiXson/pxnBackrooms-mirror#13]
### Currently the hotel rooms looks cool! but if  #12 and  #11 are fixed, I want to request slighty tweaked generation of the hotel rooms

**Currently hotel rooms with no resource pack** (yes the floor is hand replaced due #12 ).
![2023-12-27_22 29 30](https://github.com/PoiXson/pxnBackrooms-mirror/assets/128033443/33de5203-4e90-45dd-bd1e-cf446cc69c37)

**With resource pack.**
![2023-12-27_22 29 54](https://github.com/PoiXson/pxnBackrooms-mirror/assets/128033443/5706b03e-82a5-4288-9052-dff04e08dd35)

**But this is what the hotel rooms should look like with no resource pack** (slighty tweaked generation request).
![2023-12-27_22 26 34](https://github.com/PoiXson/pxnBackrooms-mirror/assets/128033443/d85d43c6-76a1-45a4-b37e-090e41a8a1c7)

**So it can support this specific look.**
![2023-12-27_22 27 06](https://github.com/PoiXson/pxnBackrooms-mirror/assets/128033443/0b075dd2-e8d4-476c-ad96-36ed1cb5de98)

### **So what needs to be added or changed?**

- replace the dark oak doors with mangrove doors.

- add an three block high line in the middel of the hotel wall, that goes to from door frame to door frame.

**Comment by lorenzop** [comment]
![Screenshot_20231228_022753](https://github.com/PoiXson/pxnBackrooms-mirror/assets/1291605/24cb1632-679d-47a6-9c97-8d56c1d95b1e)

that does look pretty good

it's a difficult thing to do though. definitely doable. the ceiling too.

**Comment by AnatomyKing** [comment]
> ![Screenshot_20231228_022753](https://private-user-images.githubusercontent.com/1291605/293158715-24cb1632-679d-47a6-9c97-8d56c1d95b1e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3NTc4ODcsIm5iZiI6MTcwMzc1NzU4NywicGF0aCI6Ii8xMjkxNjA1LzI5MzE1ODcxNS0yNGNiMTYzMi02NzlkLTQ3YTYtOWM5Ny04ZDU2YzFkOTViMWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjhUMDk1OTQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTFhNGIxZTA2M2UwZTA5YThhOThlMjc0MjFlZGQyNTZlNmI5NGNmMDlmODg1ZDA2YTA2OGRkNzQxNjM2OTIyZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.K7cccoYEQshev0C2pCPAsRzBsjZVCqClF513lH9V8J0)
> 
> that does look pretty good
> 
> it's a difficult thing to do though. definitely doable.


Yoooo!! amazing! I love that you made use of the different wallpapers! would be neat if you can use your own block in the config as wallpaper! I will look if I can fix this my self, if so I will make a bunch of cool color variations of my carpert and wallpaper texture !

**Comment by lorenzop** [comment]
added hotel walls and guest doors to the config
