### ISSUE TITLE
making Level 6 Lights Out invisible player optional

### ISSUE THREAD

**Issue by AnatomyKing** [PoiXson/pxnBackrooms-mirror#17]
Currently level lights out makes your player invisible. It's a cool mechanic. But I would highly appricate if this mechanic is optional. So I can turn this feature on and off in the config. 

### Why optional, it's such a cool mechanic?

Because my server will be a survival server, and you will have the option to go to the backrooms. But I also will have a /home or /spawn command. Players can abuse this mechanic, by making them selfs invisible and teleporting back to spawn or their base. Making a invisibility potion obsolete. I also don't want invisible players running around, because this will have an advance in combat, this would be unfair.

**Comment by lorenzop** [comment]
added this config option in commit a6043c7

still need to fix this problem. we have 2 options

1. keep the infinite time invisibility effect and use a PlayerChangedWorld event listener to make the player visible again.
2. change to a 5 second invisibility effect and update it every 2 seconds while in level 6.

**Comment by lorenzop** [comment]
fixed in 280780e 5 second invisibility refreshes every few seconds while player is in level 6
