### ISSUE TITLE
level 1 basement wells go to level 94 motion, doesn't work

### ISSUE THREAD

**Issue by AnatomyKing** [PoiXson/pxnBackrooms-mirror#18]
a5927877693260ae0631452e5c331a74ba98134e, doesn't work. When I jump in the well I die I the void. but 1482906b680ee4eaff6f6fcfd27ba6319567cdb2 does work, so maybe make a5927877693260ae0631452e5c331a74ba98134e more similar to 1482906b680ee4eaff6f6fcfd27ba6319567cdb2.

a5927877693260ae0631452e5c331a74ba98134e, doesn't work.
https://github.com/PoiXson/pxnBackrooms-mirror/assets/128033443/10d7b8eb-63b6-4876-952b-3a6585eb8134

1482906b680ee4eaff6f6fcfd27ba6319567cdb2, works good!!
https://github.com/PoiXson/pxnBackrooms-mirror/assets/128033443/8b5df4fe-c4fd-4d5d-94fc-a37952fba158

(extra info, my Thresh-Well is 2.0, so it will generate the well more frequently)

**Comment by lorenzop** [comment]
most of the thresh values go from -1.0 to 1.0, and usually a lower value will make it more common, but it all depends on how the numbers are used in the code.

I found a bug, Thresh-Well actually does nothing at all. it's not used anywhere in the code. the way it really works, it uses the generated noise and puts a well at the peaks of the noise, wherever the highest values are. changing Noise-Well-Freq to a slightly higher number will make wells more common. default value for this is 0.0028, changing it to 0.028 by removing a zero makes wells very common, too common. see screenshot.

![Screenshot_20231229_233003](https://github.com/PoiXson/pxnBackrooms-mirror/assets/1291605/6a0b56a4-ddc6-4c79-b820-b1713da0d868)

**Comment by lorenzop** [comment]
fixed this in 55bfac3

the event listener was looking for level 0 because the world is level0, but I recently improved the functions which find what level the player is in, so it started returning the proper number which is level 1 basement.

also found the grass block has been renamed to short_grass. fixed this in level 94 motion, and added tall grass.

**Comment by AnatomyKing** [comment]
> most of the thresh values go from -1.0 to 1.0, and usually a lower value will make it more common, but it all depends on how the numbers are used in the code.
> 
> I found a bug, Thresh-Well actually does nothing at all. it's not used anywhere in the code. the way it really works, it uses the generated noise and puts a well at the peaks of the noise, wherever the highest values are. changing Noise-Well-Freq to a slightly higher number will make wells more common. default value for this is 0.0028, changing it to 0.028 by removing a zero makes wells very common, too common. see screenshot. the higher noise frequency makes the peaks closer together. a lower noise frequency spreads out the noise.
> 
> ![Screenshot_20231229_233003](https://private-user-images.githubusercontent.com/1291605/293443191-6a0b56a4-ddc6-4c79-b820-b1713da0d868.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5Mjk1NjAsIm5iZiI6MTcwMzkyOTI2MCwicGF0aCI6Ii8xMjkxNjA1LzI5MzQ0MzE5MS02YTBiNTZhNC1kZGM2LTRjNzktYjgyMC1iMTcxM2RhMGQ4NjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDIzMTIzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMzBUMDk0MTAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Zjg0YTM2NDU2ZjA3YmNhM2E1Zjk0Zjk3MDk3MTBkNTI2OThjYzQyY2IxZmFiZGE1NjI2ODgzOTMyZTA3NjcwZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.DwONYNjk_Pb6Qqos1pzy7Vg83W3lB5lW6TJrwaEy0rk)

Ohh! I see, quite intresting how that works. lower number means more spread, cool!! very neat.
