### ISSUE TITLE
Level 771 barrier blocks and config

### ISSUE THREAD

**Issue by AnatomyKing** [PoiXson/pxnBackrooms-mirror#22]
Hi! peemon wanted to go to level 1 from level 771, but it's not possible due the barrier blocks that level 771 has( I think you forgot you added these lol)

So my suggestion is to remove them. Also a config for level 771 blocks would be nice, since it's the only level that doesn't have that

![2024-01-05_10 50 20](https://github.com/PoiXson/pxnBackrooms-mirror/assets/128033443/f99b2f7d-e915-44bf-96cf-db183f2fa0ca)
![image](https://github.com/PoiXson/pxnBackrooms-mirror/assets/128033443/3ca0a764-a792-4e28-adea-dba2e7e808c8)

**Comment by lorenzop** [comment]
there is an exit, just difficult to find. from the upper level, one of the pillars will be hollow with 4 trapdoors at the top. that pillar drops through into the void.

todo: make the exit more common
todo: add block types to the config

**Comment by lorenzop** [comment]
fixed the barrier blocks and added blocks to the config. now you can fall forever. there is still an exit by falling into the void, but it's only under the bridge, so you have to find the exit
