### ISSUE TITLE
Level 11 error

### ISSUE THREAD

**Issue by AnatomyKing** [PoiXson/pxnBackrooms-mirror#23]
I tested a couple versions and I don't get the error when I use **pxnPluginLib** `4.0.50` and **pxnBackrooms** `0.1.32`. So the bug was introduced in anything higher than that. 

error info,
**PaperMC** `1.20.4`
**pxnPluginLib** `4.0.51`
**pxnBackrooms** `0.1.35`
https://mclo.gs/8LC0cRa

I belevie it's due to this function removal [114f224ae6646401240bed04f6328498876d8100](https://github.com/PoiXson/pxnPluginLib-mirror/commit/114f224ae6646401240bed04f6328498876d8100) inside **pxnPluginLib**. maybe it was used inside level 11 and now since it's gone it can't load the world. But this is just a wild guess.

**Comment by lorenzop** [comment]
found the problem, fixed in 980143b

problem was it was looking for the y spawn location of level 0 inside level 11. my bad.
