### ISSUE TITLE
Level 111 is seen as The End 

### ISSUE THREAD

**Issue by AnatomyKing** [PoiXson/pxnBackrooms-mirror#24]
When you go to level 111, you get End Block recipes and it spawns the Enderdragon, so that means this level is seen by Minecraft as The End

![2024-05-06_17 39 16](https://github.com/PoiXson/pxnBackrooms-mirror/assets/128033443/9488eda3-568b-4954-9fa8-b1563268b3fb)

**Comment by AnatomyKing** [comment]
Ignore the Macrus & Slover bar

**Comment by lorenzop** [comment]
fixed in bba9378
changed back to normal always night
