### ISSUE TITLE
on Level 000 the lobby, the Wall-Base doesn't generate 

### ISSUE THREAD

**Issue by AnatomyKing** [PoiXson/pxnBackrooms-mirror#25]
I tested it with pxnPluginLib-4.0.57 and pxnBackrooms-0.1.46
the walls were generating like this
![2024-05-06_17 53 35](https://github.com/PoiXson/pxnBackrooms-mirror/assets/128033443/f7997397-ac6c-4d6a-ace5-37e79c94465f)

now on the latest dev build pxnPluginLib-4.0.59 and pxnBackrooms-0.1.50
the walls are generating like this
![2024-05-06_17 51 07](https://github.com/PoiXson/pxnBackrooms-mirror/assets/128033443/bbf1abb9-093d-4c0a-976d-13cae943de04)

so in the latest the config or generation of `Wall-Base` doesn't work

**Comment by lorenzop** [comment]
fixed in ba099a3
