### ISSUE TITLE
The portal from level 0 lobby to level 37 poolrooms stops at level 6 lightsout

### ISSUE THREAD

**Issue by AnatomyKing** [PoiXson/pxnBackrooms-mirror#26]
As you can see here in the pictures. The entrance portal that goes to the poolrooms, now gets cutt of at level 6 instead of level 37

![2024-05-06_20 27 12](https://github.com/PoiXson/pxnBackrooms-mirror/assets/128033443/c60fe9de-9c63-4a34-8c2b-27e9d59e597e)
![2024-05-06_20 27 17](https://github.com/PoiXson/pxnBackrooms-mirror/assets/128033443/29165769-ed1d-495b-a30a-48a617feee7e)
![2024-05-06_20 27 21](https://github.com/PoiXson/pxnBackrooms-mirror/assets/128033443/a716f4e6-19fe-433d-b2bc-ae39c495f489)

**Comment by lorenzop** [comment]
fixed in a8b97fd
y locations were wrong due to adding the new level 96 above level 0 - simplified the math a bit to avoid this in the future, can use level_096 - level_000 to find the height
