### ISSUE TITLE
the levers that get you to level 6 generate in the floor

### ISSUE THREAD

**Issue by AnatomyKing** [PoiXson/pxnBackrooms-mirror#27]
The levers now generate inside the floor instead of on the wall

![2024-05-06_20 21 18](https://github.com/PoiXson/pxnBackrooms-mirror/assets/128033443/ccf32c1f-5156-4d59-86e1-c2d4d88c84da)
![2024-05-06_20 21 28](https://github.com/PoiXson/pxnBackrooms-mirror/assets/128033443/8c22e126-e492-4993-ac5b-fbba42b1ef68)

**Comment by lorenzop** [comment]
fixed in 505dcf2
y location changed due to adding of bedrock barriers
