### ISSUE TITLE
The Well portals don't generate 

### ISSUE THREAD

**Issue by AnatomyKing** [PoiXson/pxnBackrooms-mirror#28]
I really searched a long time and checked the locs folder, put I can't find or it doesn't generate a Well portal from level 1 basement to level 94 motion.

you mentioned in a other issue that removing a 0 from the noise will make wells common very common. so changing it to `Noise-Well-Freq: 0.028`, but sadly that didn't do anything. https://github.com/PoiXson/pxnBackrooms-mirror/issues/18#issuecomment-1872449754

**Comment by lorenzop** [comment]
fixed in 52ddd8d
the wells may have been generating inside the ground, since adding bedrock barriers. rewrote this code to work better and a bit simpler
