### ISSUE TITLE
Buttons from level 6 to level 111 don't generate

### ISSUE THREAD

**Issue by AnatomyKing** [PoiXson/pxnBackrooms-mirror#29]
They do appear in the locs folder, but when I teleport to the location, the button isn't there
![image](https://github.com/PoiXson/pxnBackrooms-mirror/assets/128033443/6662bf4e-89c0-4b22-8751-83fa3e173c0a)

**Comment by lorenzop** [comment]
I think this was related to bug https://github.com/PoiXson/pxnBackrooms-mirror/issues/27

should be fixed now. I think the buttons were generating in the floor and maybe being overwritten.

please reopen this issue if it's still a problem
