### ISSUE TITLE
Portal ladder from level 19 to level 309 needs to be 2 blocks higher

### ISSUE THREAD

**Issue by AnatomyKing** [PoiXson/pxnBackrooms-mirror#30]
Currently the portal ladder can't be accessed without breaking blocks

![2024-05-07_00 19 30](https://github.com/PoiXson/pxnBackrooms-mirror/assets/128033443/355560a1-7773-4790-a732-d6131091a120)

**Comment by lorenzop** [comment]
fixed in 5a8dccb
this was due to adding bedrock barriers between levels
